### ISSUE TITLE
Translator module not working

### ISSUE THREAD

**Issue by note2subrata** [ruoccofabrizio/azure-open-ai-embeddings-qna#45]
Traceback (most recent call last): File "/usr/local/src/myscripts/OpenAI_Queries.py", line 39, in check_deployment llm_helper.translator.translate("This is a test", "it") File "/usr/local/src/myscripts/utilities/translator.py", line 26, in translate if (response[0]['language'] != language): KeyError: 0

We tested with key provided in a test script, its working.

**Comment by note2subrata** [comment]
using incorrect endpoint; resolved
