### ISSUE TITLE
Check deployment after "Deploy to Azure"

### ISSUE THREAD

**Issue by pierlag** [ruoccofabrizio/azure-open-ai-embeddings-qna#47]
Error embedding check with  text-embedding-ada-002 existed on Azure. Test error with V1 and V2 model.

Embedding model is not working. Please check you have a deployment name text-embedding-ada-002 in your Azure OpenAI resource https://xxx.openai.azure.com/. Then restart your application.

Traceback (most recent call last): File "/usr/local/src/myscripts/OpenAI_Queries.py", line 28, in check_deployment llm_helper.embeddings.embed_documents(texts=["This is a test"]) File "/usr/local/lib/python3.9/site-packages/langchain/embeddings/openai.py", line 258, in embed_documents return self._get_len_safe_embeddings(texts, engine=self.document_model_name) File "/usr/local/lib/python3.9/site-packages/langchain/embeddings/openai.py", line 194, in _get_len_safe_embeddings encoding = tiktoken.model.encoding_for_model(self.document_model_name) File "/usr/local/lib/python3.9/site-packages/tiktoken/model.py", line 51, in encoding_for_model raise KeyError( KeyError: 'Could not automatically map text-embedding-ada-002 to a tokeniser. Please use tiktok.get_encoding to explicitly get the tokeniser you expect.'

**Comment by ruoccofabrizio** [comment]
hi @pierlag please check your deployment name in your Azure OpenAI resource for the embedding model.

![Screenshot 2023-04-11 190756](https://user-images.githubusercontent.com/22171838/231237987-4cbd7098-a2b8-4398-91ca-a4232d0cbaad.jpg)

**Comment by ruoccofabrizio** [comment]
@SamOyeAH Please moderate your language. And the answer is exactly as it should be. The deployment name has to match the text-embedding-ada-002 model name, as shown in the image.
