### ISSUE TITLE
Error uploading files

### ISSUE THREAD

**Issue by jacktong007** [ruoccofabrizio/azure-open-ai-embeddings-qna#52]
PDF file，39.9M
send raise error azure.core.exceptions.ServiceResponseError: ('Connection aborted.', timeout('The write operation timed out'))

**Comment by ruoccofabrizio** [comment]
Could you please provide more details on the operation you are trying and a full log? Thanks

**Comment by jacktong007** [comment]
Traceback (most recent call last): File "/root/azure-open-ai-embeddings-qna/code/pages/01_Add_Document.py", line 84, in <module> llm_helper.blob_client.upsert_blob_metadata(uploaded_file.name, {'converted': 'true', 'embeddings_added': 'true', 'converted_filename': converted_filename}) File "/root/azure-open-ai-embeddings-qna/code/utilities/azureblobstorage.py", line 62, in upsert_blob_metadata blob_client.set_blob_metadata(metadata= blob_metadata) File "/usr/local/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer return func(*args, **kwargs) File "/usr/local/lib/python3.9/site-packages/azure/storage/blob/_blob_client.py", line 1459, in set_blob_metadata return self._client.blob.set_metadata(**options) # type: ignore File "/usr/local/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer return func(*args, **kwargs) File "/usr/local/lib/python3.9/site-packages/azure/storage/blob/_generated/operations/_blob_operations.py", line 2725, in set_metadata pipeline_response = self._client._pipeline.run( # type: ignore # pylint: disable=protected-access File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 202, in run return first_node.send(pipeline_request) File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 70, in send response = self.next.send(request) File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 70, in send response = self.next.send(request) File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 70, in send response = self.next.send(request) [Previous line repeated 2 more times] File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/policies/_redirect.py", line 156, in send response = self.next.send(request) File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 70, in send response = self.next.send(request) File "/usr/local/lib/python3.9/site-packages/azure/storage/blob/_shared/policies.py", line 520, in send response = self.next.send(request) File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 70, in send response = self.next.send(request) File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 70, in send response = self.next.send(request) File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 70, in send response = self.next.send(request) [Previous line repeated 1 more time] File "/usr/local/lib/python3.9/site-packages/azure/storage/blob/_shared/policies.py", line 313, in send response = self.next.send(request) File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 70, in send response = self.next.send(request) File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 70, in send response = self.next.send(request) File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 101, in send self._sender.send(request.http_request, **request.context.options), File "/usr/local/lib/python3.9/site-packages/azure/storage/blob/_shared/base_client.py", line 335, in send return self._transport.send(request, **kwargs) File "/usr/local/lib/python3.9/site-packages/azure/core/pipeline/transport/_requests_basic.py", line 326, in send response = self.session.request( # type: ignore File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request resp = self.send(prep, **send_kwargs) File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send r = adapter.send(request, **kwargs) File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 489, in send resp = conn.urlopen( File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen httplib_response = self._make_request( File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request conn.request(method, url, **httplib_request_kw) File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 244, in request super(HTTPConnection, self).request(method, url, body=body, headers=headers) File "/usr/lib64/python3.9/http/client.py", line 1257, in request self._send_request(method, url, body, headers, encode_chunked) File "/usr/lib64/python3.9/http/client.py", line 1298, in _send_request self.putheader(hdr, value) File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 224, in putheader _HTTPConnection.putheader(self, header, *values) File "/usr/lib64/python3.9/http/client.py", line 1230, in putheader values[i] = one_value.encode('latin-1') UnicodeEncodeError: 'latin-1' codec can't encode characters in position 20-24: ordinal not in range(256)

**Comment by ruoccofabrizio** [comment]
What's the filename?

**Comment by jacktong007** [comment]
I have tried several files and the filenames are all in Chinese, for example one of the filenames is Geek+ DMS用户使用手册.pdf
After uploading the document, you can see the status of the document in the document viewer: converted is yes, embeddings_added status is no; but mention in chat about the content of this document, and can be more accurate answer。
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/129478485/233826230-89a560b6-8ceb-4e8e-9a1f-e2dd18f2f181.png">
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/129478485/233826270-5ce789e6-3e5f-4eea-9f53-319544160ea6.png">

**Comment by ruoccofabrizio** [comment]
Thanks @jacktong007 the issue was related to the metadata setting in the Azure Blob Storage with not Latin characters. As you said, the file was correctly added but the metadata used to show the "embeddings_added" in the table was missing due to an encoding issue.
