### ISSUE TITLE
long error when running

### ISSUE THREAD

**Issue by Sequential-circuits** [ruoccofabrizio/azure-open-ai-embeddings-qna#63]
Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 698, in connect sock = self.retry.call_with_retry( File "/usr/local/lib/python3.9/site-packages/redis/retry.py", line 46, in call_with_retry return do() File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 699, in <lambda> lambda: self._connect(), lambda error: self.disconnect(error) File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 955, in _connect for res in socket.getaddrinfo( File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo for res in _socket.getaddrinfo(host, port, family, type, proto, flags): socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last): File "/usr/local/src/myscripts/OpenAI_Queries.py", line 120, in <module> llm_helper = LLMHelper(custom_prompt=st.session_state.custom_prompt, temperature=st.session_state.custom_temperature) File "/usr/local/src/myscripts/utilities/helper.py", line 90, in init self.vector_store: RedisExtended = RedisExtended(redis_url=self.vector_store_full_address, index_name=self.index_name, embedding_function=self.embeddings.embed_query) if vector_store is None else vector_store File "/usr/local/src/myscripts/utilities/redis.py", line 26, in init super().init(redis_url, index_name, embedding_function) File "/usr/local/lib/python3.9/site-packages/langchain/vectorstores/redis.py", line 90, in init _check_redis_module_exist(redis_client, REDIS_REQUIRED_MODULES) File "/usr/local/lib/python3.9/site-packages/langchain/vectorstores/redis.py", line 30, in _check_redis_module_exist installed_modules = client.module_list() File "/usr/local/lib/python3.9/site-packages/redis/commands/core.py", line 5761, in module_list return self.execute_command("MODULE LIST") File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1255, in execute_command conn = self.connection or pool.get_connection(command_name, **options) File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 1442, in get_connection connection.connect() File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 704, in connect raise ConnectionError(self._error_message(e)) redis.exceptions.ConnectionError: Error -2 connecting to api:6379. Name or service not known.

**Comment by ruoccofabrizio** [comment]
which method are you using to run the solution? when using api:6379 as the Redis stack address, it points to the docker container running within the docker network. So, it's suitable only for the docker-compose mode.

**Comment by ruoccofabrizio** [comment]
I suppose you solved it as I didn't hear back. Closing the issue as it's your config to be changed. Write back if you didn't solve it.
